### ISSUE TITLE
Fatal Error when installing plugin via wp.org

### ISSUE THREAD

**Issue by josephfusco** [campuspress/code-check#5]
When downloading this repo on GitHub and using the plugin it works great, however installing the plugin via the wp.org plugin directory causes a fatal error on `wp-admin/themes.php?page=campus-themecheck` & `wp-admin/plugins.php?page=campus-plugincheck`.

![screen shot 2017-07-12 at 15 13 35](https://user-images.githubusercontent.com/6676674/28135667-0e083874-6715-11e7-827a-11f8fbc60a86.png)

**Comment by igmoweb** [comment]
@josephfusco Fixed and released
